# Generated by Django 4.2 on 2023-04-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_salt_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to='user.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='user.user')),
            ],
        ),
    ]
